version: '3.9'

services:
  app:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG=1
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_DB=emergencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=emergencies
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" 
volumes:
  postgres_data:
  static_files: