# Generated by Django 4.1 on 2022-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=500)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("location", models.CharField(max_length=500)),
                ("message", models.CharField(max_length=500)),
                ("level", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "emergencies",
            },
        ),
    ]
