version: "3.8"
   
services:
    master:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - .:/usr/src/app/
        ports:
            - "8080:8080"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A masterapp worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - master
            - redis
    redis:
        image: "redis:alpine"